### ISSUE TITLE
Doesnt work with blender 4.2

### ISSUE THREAD

**Issue by stealbe** [Sollumz/Sollumz#971]
Hey, 
I used the addon for 3 months and everything was good, but today during another project it started giving errors for any action, when trying to install it an error appears:

>`Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Sollumz\ytyp\gizmos\mlo.py", line 104, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'`

ValueError: register_class(...): allready registered as a subclass 'portalGizmoGroup'

Afterwards I downloaded the latest release but it didn't help.

**Comment by ook3D** [comment]
you need to download the latest commit, as the latest release does not support blender 4.2

**Comment by stealbe** [comment]
but I've had blender 4.2 for quite a long time now and everything was fine until now

> вам необходимо загрузить последнюю версию, так как последняя версия не поддерживает blender 4.2

**Comment by Hancapo** [comment]
Download the latest commit.

**Comment by stealbe** [comment]
I currently have version 2.4.2-dev+bf06afd, isn't that the latest commit? Drop pls link for last commit

**Comment by alexguirre** [comment]
> I currently have version 2.4.2-dev+bf06afd, isn't that the latest commit? Drop pls link for last commit
That's the correct version, yes.

The problem is that the error `AttributeError: 'Scene' object has no attribute 'show_room_gizmo'` doesn't help much because it is just a side-effect of some error during initialization. You could try opening the System Console right after opening Blender, scroll up to the beginning and try to find some different error.

Also, make sure you don't have any other Sollumz version installed.

**Comment by stealbe** [comment]
full list of errores
at install:

> `File contains no section headers.
file: 'C:\\Users\\parad\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\config\\sollumz_prefs.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 260, in draw
    if context.scene.sollumz_export_path != "":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'sollumz_export_path'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 358, in poll
    preferences = get_addon_preferences(bpy.context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_preferences.py", line 387, in get_addon_preferences
    return context.preferences.addons[__package__].preferences
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "bl_ext.user_default.sollumz_dev" not found'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 250, in refresh
    selected_archetype = get_selected_archetype(context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 20, in get_selected_archetype
    ytyp = get_selected_ytyp(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 104, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 116, in draw_prepare
    selected_ytyp = get_selected_ytyp(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`
when starting the addon everything is the same

**Comment by stealbe** [comment]
> > У меня сейчас версия 2.4.2-dev+bf06afd, разве это не последний коммит? Скиньте пожалуйста ссылку на последний коммит
> 
> Да, это правильная версия.
> 
> Проблема в том, что ошибка `AttributeError: 'Scene' object has no attribute 'show_room_gizmo'`не помогает, потому что это просто побочный эффект какой-то ошибки во время инициализации. Вы можете попробовать открыть системную консоль сразу после открытия Blender, прокрутить до начала и попытаться найти какую-то другую ошибку.
> 
> Также убедитесь, что у вас не установлена ​​какая-либо другая версия Sollumz.

full list of errores
at install:

> `File contains no section headers.
file: 'C:\\Users\\parad\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\config\\sollumz_prefs.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 260, in draw
    if context.scene.sollumz_export_path != "":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'sollumz_export_path'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 358, in poll
    preferences = get_addon_preferences(bpy.context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_preferences.py", line 387, in get_addon_preferences
    return context.preferences.addons[__package__].preferences
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "bl_ext.user_default.sollumz_dev" not found'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 250, in refresh
    selected_archetype = get_selected_archetype(context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 20, in get_selected_archetype
    ytyp = get_selected_ytyp(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 104, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 116, in draw_prepare
    selected_ytyp = get_selected_ytyp(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`
when starting the addon everything is the same

**Comment by stealbe** [comment]
> > I currently have version 2.4.2-dev+bf06afd, isn't that the latest commit? Drop pls link for last commit
> 
> That's the correct version, yes.
> 
> The problem is that the error `AttributeError: 'Scene' object has no attribute 'show_room_gizmo'` doesn't help much because it is just a side-effect of some error during initialization. You could try opening the System Console right after opening Blender, scroll up to the beginning and try to find some different error.
> 
> Also, make sure you don't have any other Sollumz version installed.

full list of errores
at install:

> `File contains no section headers.
file: 'C:\\Users\\parad\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\config\\sollumz_prefs.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 260, in draw
    if context.scene.sollumz_export_path != "":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'sollumz_export_path'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_ui.py", line 358, in poll
    preferences = get_addon_preferences(bpy.context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\sollumz_preferences.py", line 387, in get_addon_preferences
    return context.preferences.addons[__package__].preferences
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "bl_ext.user_default.sollumz_dev" not found'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 250, in refresh
    selected_archetype = get_selected_archetype(context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 20, in get_selected_archetype
    ytyp = get_selected_ytyp(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 104, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 116, in draw_prepare
    selected_ytyp = get_selected_ytyp(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\utils.py", line 16, in get_selected_ytyp
    return get_list_item(scene.ytyps, scene.ytyp_index)
                         ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'ytyps'
`

> `Python: Traceback (most recent call last):
  File "C:\Users\parad\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\sollumz_dev\ytyp\gizmos\mlo.py", line 235, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
`
when starting the addon everything is the same

**Comment by alexguirre** [comment]
Huh, your sollumz_prefs.ini looks completely broken. Try deleting that file: `C:\\Users\\parad\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\config\\sollumz_prefs.ini`

**Comment by stealbe** [comment]
It works, thanks!

> Huh, your sollumz_prefs.ini looks completely broken. Try deleting that file: `C:\\Users\\parad\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\config\\sollumz_prefs.ini`
